name: jeffjones
favicon: null
layout_spectrum: 0.58737
typography_spectrum: 0.4859
title: Jeff Jones
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#062e6c'
    - '#feeebb'
    - '#435972'
    - '#748691'
    - '#c7ceb3'
  brandStrength: 0.5122760920785367
  lightness: 0
  saturation: 0.9940858043264598
  rhythmicContrast: 0.5
purpose: []
