name: jeffjones
favicon: null
layout_spectrum: 0.9710385855287313
typography_spectrum: 0.6834282150957733
title: Jeff Jones
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5122760920785367
  lightness: 0.8649396875407547
  saturation: 0.9940858043264598
  rhythmicContrast: 0.05750791681930423
purpose: []
